# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VdElCB37Zdh5gN2lcHtQ7kxpfvVOetwr
"""

import streamlit as st
import joblib
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# -------------------- PAGE CONFIG --------------------
st.set_page_config(
    page_title="Airbnb AI Pricing",
    layout="wide",
    page_icon="🏡"
)

# -------------------- CUSTOM STYLE --------------------
st.markdown("""
    <style>
    .main {
        background-color: #f7f9fc;
    }
    h1 {
        color: #ff5a5f;
    }
    .stMetric {
        background-color: #ffffff;
        padding: 10px;
        border-radius: 10px;
        box-shadow: 0px 2px 6px rgba(0,0,0,0.05);
    }
    </style>
""", unsafe_allow_html=True)

# -------------------- LOAD DATA --------------------
@st.cache_data
def load_data():
    df = pd.read_csv("dublin_aggregated_df(1).csv")
    raw_df = pd.read_csv('dublin_merged_df(1).csv.gz', compression='gzip')
    raw_df['host_since'] = pd.to_datetime(raw_df['host_since'])
    raw_df['first_review'] = pd.to_datetime(raw_df['first_review'])
    raw_df['date'] = pd.to_datetime(raw_df['date'])
    raw_df['month'] = raw_df['date'].dt.month
    return df, raw_df

@st.cache_resource
def load_model():
    return joblib.load('xgb_model_log(1).pkl')

df, raw_df = load_data()
model = load_model()

# -------------------- HEADER --------------------
st.title("🏡 Airbnb Price Prediction System")
st.markdown("### AI-powered pricing tool for smarter Airbnb listings")

# -------------------- KPI METRICS --------------------
col1, col2, col3 = st.columns(3)

col1.metric("📊 Avg Price", f"€{round(df['price'].mean(), 2)}")
col2.metric("⭐ Overall Rating", round(df['review_scores_rating'].mean(), 2))
col3.metric("🏘️ Listings", len(df))

# -------------------- TABS --------------------
tab1, tab2, tab3, tab4 = st.tabs(["📊 Dashboard", "📈 Visual Insights", "🧠 Model Insights", "🤖 Prediction"])

# -------------------- TAB 1 --------------------
with tab1:
    st.subheader("Dataset Overview")
    st.dataframe(df, use_container_width=True)

# -------------------- TAB 2 --------------------
with tab2:
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Price vs Rating")
        st.scatter_chart(df, x='price', y='review_scores_rating')

        top_types = raw_df['property_type'].value_counts().nlargest(10).index
        pt_data = raw_df[raw_df['property_type'].isin(top_types)] \
            .groupby('property_type')['price'].mean().reset_index()

        st.subheader("Top Property Types")
        st.bar_chart(pt_data, x='property_type', y='price')

    with col2:
        st.subheader("Price Distribution")
        fig, ax = plt.subplots()
        ax.hist(df['price'], bins=20)
        st.pyplot(fig)

        monthly = raw_df.groupby('month')['price'].mean().reset_index()
        monthly['month'] = pd.to_datetime(monthly['month'], format='%m').dt.strftime('%B')
        st.subheader("Monthly Trends")
        st.line_chart(monthly, x='month', y='price')

    st.subheader("Geographical Distribution")
    st.map(raw_df.sample(1000), latitude='latitude', longitude='longitude', width='stretch')

# -------------------- ENCODING --------------------
@st.cache_data
def calculate_frequency_encodings(neighbourhood, property_type, df):
    n_freq = df[df['neighbourhood'] == neighbourhood]['neighbourhood_freq'].mean()
    p_freq = df[df['property_type'] == property_type]['property_type_freq'].mean()

    if pd.isna(n_freq):
        n_freq = df['neighbourhood_freq'].mean()
    if pd.isna(p_freq):
        p_freq = df['property_type_freq'].mean()

    return n_freq, p_freq
# -------------------- TAB 3: MODEL & MARKET INSIGHTS --------------------
with tab3:
    st.subheader("Model Performance & Reliability")

    # --- 1. Evaluation Metrics ---
    col_m1, col_m2, col_m3 = st.columns(3)
    with col_m1:
        st.metric("R² Score", "0.6925", help="Explains 69% of price variance. Higher is better.")
    with col_m2:
        st.metric("Test RMSE (Log)", "0.3910", help="Root Mean Squared Error on log-transformed prices.")
    with col_m3:
        st.metric("Test MAE (Log)", "0.2665", help="Mean Absolute Error. Roughly 26-30% error in Euro terms.")

    st.markdown("---")

    # --- 2. Market Growth Trends (Corrected Visual 1) ---
    st.subheader("📅 Dublin Market Growth Trends")
    
    try:
        # Prepare data for time-series: Convert to datetime and drop NaNs
        # We do this locally to ensure the index is clean for resampling
        ts_df = raw_df.copy()
        ts_df['host_since'] = pd.to_datetime(ts_df['host_since'], errors='coerce')
        ts_df['first_review'] = pd.to_datetime(ts_df['first_review'], errors='coerce')

        fig_time, ax_time = plt.subplots(figsize=(15, 6))

        # Plot 1: Hosts joining (Resampled by Month Start 'MS')
        ts_df.dropna(subset=['host_since']).set_index('host_since').resample('MS').size().plot(
            label='New Hosts Joining Airbnb', color='orange', ax=ax_time, linewidth=2
        )

        # Plot 2: Listings getting first review
        ts_df.dropna(subset=['first_review']).set_index('first_review').resample('MS').size().plot(
            label='Listings Getting First Review', color='red', ax=ax_time, alpha=0.7
        )

        ax_time.set_title('Dublin Host Acquisition vs. Listing Activation', fontsize=14)
        ax_time.set_xlim('2009-11-25', '2025-04-30')
        ax_time.set_xlabel('Year')
        ax_time.set_ylabel('Count of Events')
        ax_time.legend()
        
        st.pyplot(fig_time)
    except Exception as e:
        st.error(f"Error rendering time-series: {e}")

    st.markdown("---")

    # --- 3. Feature Importance & Correlation ---
    col_left, col_right = st.columns([2, 1])

    with col_left:
        st.subheader("📊 Feature Importance (XGBoost)")
        
        # Accessing the model from the pipeline
        if hasattr(model, "named_steps"):
            model_step = model.named_steps.get('xgb', model)
        else:
            model_step = model

        if hasattr(model_step, 'feature_importances_'):
            feature_names = [
                'host_response_rate', 'host_is_superhost', 'host_listings_count', 
                'accommodates', 'bedrooms', 'beds', 'review_scores_rating', 
                'number_of_reviews', 'review_scores_cleanliness', 
                'review_scores_location', 'maximum_nights', 
                'neighbourhood_freq', 'property_type_freq'
            ]
            # Ensure the feature names match the model's expected input count
            fi = pd.DataFrame({
                "Feature": feature_names, 
                "Importance": model_step.feature_importances_
            }).sort_values(by="Importance", ascending=True)
            
            fig_fi, ax_fi = plt.subplots(figsize=(8, 6))
            ax_fi.barh(fi["Feature"], fi["Importance"], color='#ff5a5f')
            ax_fi.set_title("Key Drivers of Listing Price")
            st.pyplot(fig_fi)
        else:
            st.warning("Feature importance data is not available for this model.")

    with col_right:
        st.subheader("⚠️ Model Limitations")
        st.info("""
        **Unexplained Variance (31%)**
        The model cannot account for 'intangibles' like interior design, professional photography, or the specific view from a window.
        
        **The Log-Scale Effect**
        Because the model was trained on log-transformed prices, it is more accurate for mid-range properties than extreme luxury or budget listings.
        """)

    st.markdown("---")

    # --- 4. Correlation Matrix (Corrected Visual 2) ---
    st.subheader("🔗 Feature Correlations")
    with st.expander("View Full Correlation Heatmap"):
        import seaborn as sns
        
        # Filter for numeric only and drop columns with zero variance (all NaNs)
        numeric_df = raw_df.select_dtypes(include=['number']).dropna(axis=1, how='all')
        
        if not numeric_df.empty:
            correlation_matrix = numeric_df.corr()
            fig_corr, ax_corr = plt.subplots(figsize=(18, 10))
            sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5, ax=ax_corr)
            ax_corr.set_title("Feature Correlation Matrix")
            st.pyplot(fig_corr)
        else:
            st.warning("Not enough numeric data found to generate a correlation matrix.")

    # --- 5. Ethical Considerations ---
    st.subheader("⚖️ Ethical & Social Considerations")
    
    eth_col1, eth_col2 = st.columns(2)
    with eth_col1:
        st.markdown("""
        **Gentrification Risk**
        By suggesting prices based on 'Neighborhood Frequency,' the tool may inadvertently encourage price inflation in developing areas, impacting local housing affordability.
        """)
    with eth_col2:
        st.markdown("""
        **The Professional Bias**
        The model rewards 'Superhost' status and high response rates, favoring professional property managers over casual 'mom-and-pop' hosts.
        """)

    with st.expander("🔍 Note on Proxy Bias"):
        st.write("""
        Even without explicit demographic data, variables like 'Location Score' and 'Review Ratings' can act as proxies for human bias. 
        If travelers provide lower ratings based on subjective biases, the AI may 'learn' to devalue those listings, 
        automating existing prejudices into the pricing structure.
        """)
# -------------------- TAB 4 --------------------
with tab4:
    st.subheader("Enter Property Details")

    col1, col2 = st.columns(2)

    with col1:
        host_response_rate = st.slider("Response Rate", 0.0, 1.0, 0.9)
        host_is_superhost = st.selectbox("Superhost", ["yes", "no"])
        host_listings_count = st.number_input("Listings Count", 1, 100, 1)

    with col2:
        property_type = st.selectbox("Property Type", df['property_type'].dropna().unique())
        accommodates = st.slider("Accommodates", 1, 20, 2)
        bedrooms = st.slider("Bedrooms", 0, 10, 1)
        beds = st.slider("Beds", 1, 20, 1)

    neighbourhood = st.selectbox("Neighbourhood", df['neighbourhood'].dropna().unique())

    col3, col4 = st.columns(2)
    with col3:
        rating = st.slider("Overall Rating", 0.0, 5.0, 4.5)
        cleanliness = st.slider("Cleanliness", 0.0, 5.0, 4.5)
    with col4:
        location = st.slider("Location Score", 0.0, 5.0, 4.5)
        reviews = st.number_input("Number of Reviews", 0, 500000, 10)

    max_nights = st.slider("Max Nights", 1, 1125, 30)

    if st.button("🚀 Predict Price"):

        n_freq, p_freq = calculate_frequency_encodings(neighbourhood, property_type, df)

        input_df = pd.DataFrame([{
            'host_response_rate': host_response_rate,
            'host_is_superhost': 1 if host_is_superhost == 'yes' else 0,
            'host_listings_count': host_listings_count,
            'accommodates': accommodates,
            'bedrooms': bedrooms,
            'beds': beds,
            'maximum_nights': max_nights,
            'review_scores_rating': rating,
            'review_scores_cleanliness': cleanliness,
            'review_scores_location': location,
            'number_of_reviews': reviews,
            'neighbourhood_freq': n_freq,
            'property_type_freq': p_freq
        }])

        try:
            input_df = input_df[model.feature_names_in_]
        except:
            pass

        pred_log = model.predict(input_df)
        price = np.exp(pred_log[0])

        # 🎯 Fancy Output
        st.success(f"💰 Estimated Price: €{round(price, 2)}")

        st.metric("Predicted Price (€)", round(price, 2))

        # Confidence band (based on RMSE idea)
        st.info(f"📉 Expected range: €{round(price*0.85,2)} - €{round(price*1.15,2)}")

