# -*- coding: utf-8 -*-
"""suggestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHYT1P4IJrL782h107DrSatkb1xUo7pC
"""


import streamlit as st
import joblib
import pandas as pd
from PIL import Image
import requests
from io import BytesIO

# 1. PAGE CONFIG: Must be the first Streamlit command
st.set_page_config(page_title="Dublin StaySelect", page_icon="🍀", layout="wide")

# 2. CUSTOM CSS: Fixes the 'unsafe_allow_html' error and adds styling
st.markdown("""
    <style>
    .main { background-color: #f8f9fa; }
    div[data-testid="stMetricValue"] { color: #FF5A5F; }
    .stButton>button { width: 100%; border-radius: 20px; height: 3em; background-color: #FF5A5F; color: white; border: none; }
    .stButton>button:hover { background-color: #de3e44; color: white; }
    .reportview-container .main .block-container { padding-top: 2rem; }
    </style>
    """, unsafe_allow_html=True)

# 3. DATA LOADING
@st.cache_data
def load_data():
    # Ensure the file path is correct relative to your script
    return pd.read_csv('dublin_merged_df(1).csv.gz', compression='gzip')

@st.cache_resource
def load_suggestion_model():
    return joblib.load('recommendation_system/svd_model.pkl')

def get_image(url):
    try:
        response = requests.get(url, timeout=5)
        return Image.open(BytesIO(response.content))
    except Exception:
        return None

# 4. RECOMMENDATION LOGIC
def recommend_airbnbs(user_id, listings_df, final_model):
    try:
        all_listings = listings_df['id_x'].unique()
        user_listings = listings_df[listings_df['reviewer_id'] == user_id]['id_x'].unique()
        listings_to_predict = list(set(all_listings) - set(user_listings))
        
        # Predict ratings for unvisited listings
        user_listing_pairs = [(user_id, lid, 0) for lid in listings_to_predict]
        predictions = final_model.test(user_listing_pairs)
        
        # Sort by estimated rating and take top 5
        top_recs = sorted(predictions, key=lambda x: x.est, reverse=True)[:5]

        st.write("---")
        st.subheader(f"✨ Top Matches for Guest {user_id}")
        
        for idx, rec in enumerate(top_recs, 1):
            listing = listings_df[listings_df['id_x'] == rec.iid].iloc[0]
            
            with st.container():
                col1, col2 = st.columns([1, 2])
                
                with col1:
                    img = get_image(listing['picture_url'])
                    if img:
                        st.image(img, use_column_width=True)
                    else:
                        st.info("No Preview Image Available")

                with col2:
                    # Display metrics for quick scanning
                    m1, m2, m3 = st.columns(3)
                    m1.metric("Nightly Rate", f"€{listing['price']}")
                    m2.metric("Capacity", f"{int(listing['accommodates'])} Guests")
                    m3.metric("Beds", f"{int(listing['bedrooms'])}")
                    
                    with st.expander("Explore Property Details"):
                        st.write(listing['description'])
                        st.markdown(f"**Neighborhood:** {listing['neighbourhood']}")
                    
                    st.link_button("🔗 View Official Listing", listing['listing_url'])
                
                st.divider()
    except Exception as e:
        st.error(f"Error generating recommendations: {e}")

# 5. SIDEBAR & MAIN INTERFACE
def main():
    raw_df = load_data()
    final_model = load_suggestion_model()

    # Sidebar
    with st.sidebar:
        st.title("🍀 DublinStay")
        st.markdown("---")
        st.subheader("Quick Test Profiles")
        top_ids = raw_df['reviewer_id'].value_counts().head(5).index.tolist()
        selected_id = st.selectbox("Choose a frequent reviewer:", top_ids)
        st.info("This system uses Collaborative Filtering to predict your preferences based on Dublin's rental history.")

    # Main Hero Section
    st.title("Personalized Dublin Stays")
    st.markdown("Enter your User ID below to see your custom-curated accommodation matches.")
    
    col_a, col_b = st.columns([2, 1])
    with col_a:
        user_input = st.number_input("User ID:", value=int(selected_id))
    
    if st.button("Generate Recommendations"):
        with st.spinner('Analyzing the Dublin market for you...'):
            recommend_airbnbs(user_input, raw_df, final_model)

if __name__ == "__main__":
    main()
