# -*- coding: utf-8 -*-
"""suggestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHYT1P4IJrL782h107DrSatkb1xUo7pC
"""
import streamlit as st
import joblib
import pandas as pd
from PIL import Image
import requests
from io import BytesIO
import matplotlib.pyplot as plt
import seaborn as sns

# 1. PAGE CONFIG
st.set_page_config(page_title="Dublin StaySelect", page_icon="🍀", layout="wide")

# 2. CUSTOM CSS
st.markdown("""
    <style>
    .main { background-color: #f8f9fa; }
    div[data-testid="stMetricValue"] { color: #FF5A5F; }
    .stButton>button { width: 100%; border-radius: 20px; height: 3em; background-color: #FF5A5F; color: white; border: none; }
    .stButton>button:hover { background-color: #de3e44; color: white; }
    </style>
    """, unsafe_allow_html=True)

# 3. DATA LOADING
@st.cache_data
def load_data():
    return pd.read_csv('dublin_merged_df(1).csv.gz', compression='gzip')

@st.cache_resource
def load_suggestion_model():
    return joblib.load('recommendation_system/baseline_model.pkl')

def get_image(url):
    try:
        response = requests.get(url, timeout=5)
        return Image.open(BytesIO(response.content))
    except Exception:
        return None

# 4. RECOMMENDATION LOGIC
def recommend_airbnbs(user_id, listings_df, final_model):
    try:
        all_listings = listings_df['id_x'].unique()
        user_listings = listings_df[listings_df['reviewer_id'] == user_id]['id_x'].unique()
        listings_to_predict = list(set(all_listings) - set(user_listings))
        
        user_listing_pairs = [(user_id, lid, 0) for lid in listings_to_predict]
        predictions = final_model.test(user_listing_pairs)
        top_recs = sorted(predictions, key=lambda x: x.est, reverse=True)[:5]

        st.subheader(f"✨ Top Matches for Guest {user_id}")
        
        for idx, rec in enumerate(top_recs, 1):
            listing = listings_df[listings_df['id_x'] == rec.iid].iloc[0]
            with st.container():
                col1, col2 = st.columns([1, 2])
                with col1:
                    img = get_image(listing['picture_url'])
                    if img:
                        st.image(img, use_column_width=True)
                    else:
                        st.info("No Preview Image Available")
                with col2:
                    m1, m2, m3 = st.columns(3)
                    m1.metric("Nightly Rate", f"€{listing['price']}")
                    m2.metric("Capacity", f"{int(listing['accommodates'])} Guests")
                    m3.metric("Beds", f"{int(listing['bedrooms'])}")
                    with st.expander("Explore Property Details"):
                        st.write(listing['description'])
                        st.markdown(f"**Neighborhood:** {listing['neighbourhood']}")
                    st.link_button("🔗 View Official Listing", listing['listing_url'])
                st.divider()
    except Exception as e:
        st.error(f"Error generating recommendations: {e}")

# 5. MAIN INTERFACE
def main():
    raw_df = load_data()
    final_model = load_suggestion_model()

    # Sidebar
    with st.sidebar:
        st.title("🍀 DublinStay")
        st.subheader("📊 Model Stats")
        st.metric("Training Samples", "276,126") 
        c1, c2 = st.columns(2)
        c1.metric("RMSE", "0.4347")
        c2.metric("MAE", "0.3205")
        st.caption("BaselineOnly Model | 5-Fold CV")
        st.markdown("---")
        
        top_ids = raw_df['reviewer_id'].value_counts().head(5).index.tolist()
        selected_id = st.selectbox("Quick Test Profiles:", top_ids)
        st.info("This is a Supervised Learning system using Collaborative Filtering.")

    # Tabs for Organization
    tab1, tab2 = st.tabs(["🔍 Find Stays", "⚖️ Ethics & Insights"])

    with tab1:
        st.title("Personalized Dublin Stays")
        user_input = st.number_input("User ID:", value=int(selected_id))
        if st.button("Generate Recommendations"):
            with st.spinner('Analyzing Dublin rentals...'):
                recommend_airbnbs(user_input, raw_df, final_model)

    with tab2:
        st.header("Project Insights & Considerations")
        
        # --- ADDING THE VISUALIZATION ---
        st.subheader("📈 Sentiment Distribution")
        fig, ax = plt.subplots(figsize=(10, 4))
        # Assuming 'compound_scores' is the column name in your CSV
        sns.histplot(raw_df['compound_scores'], kde=True, ax=ax, color="#FF5A5F")
        ax.set_title("Distribution of Sentiment Scores (Training Data)")
        st.pyplot(fig)
        
        st.divider()

        col_left, col_right = st.columns(2)
        with col_left:
            st.subheader("⚠️ Technical Limitations")
            st.write(f"""
            - **Data Volume:** Trained on **276,126** records.
            - **Positivity Bias:** As seen in the chart above, most reviews are 0.8+, making it hard to find 'bad' stays.
            - **Cold Start:** New listings without reviews cannot be recommended.
            - **Sentiment vs. Reality:** 0.0 scores might be neutral or just short reviews.
            """)
        
        with col_right:
            st.subheader("🛡️ Ethical Considerations")
            st.write("""
            - **Gentrification Risk:** Promoting popular areas can impact local housing availability.
            - **Echo Chambers:** Recommending similar stays may limit user discovery of new areas.
            - **Privacy:** Reviewer IDs are used to maintain history while protecting direct identity.
            """)
        
        st.warning("Note: Recommendations are based on historical sentiment and may not reflect current property conditions.")

if __name__ == "__main__":
    main()
